export enum GameState {
    GAME_NOT_STARTED = 'GAME_NOT_STARTED',
    NOUGHTS_TURN = 'NOUGHTS_TURN',
    CROSSES_TURN = 'CROSSES_TURN',
    NOUGHTS_WINS = 'NOUGHTS_WINS',
    CROSSES_WINS = 'CROSSES_WINS',
    DRAW = 'DRAW'
}
